#!/bin/bash
#
# Copyright (c) 2014 Stephen Arnold <stephen.arnold42 _at_ gmail.com>
# License: GPL (see http://www.gnu.org/licenses/gpl.txt for a copy of the license)
#
### BEGIN INIT INFO
# Provides: cpufrequtils-init
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: set cpufrequtils governor
### END INIT INFO

# Source function library.
. /etc/init.d/functions

NAME=cpufrequtils-init
DESC="Script to set cpufrequtils governor"

# Source defaults file; edit that file to configure this script.
if [ -e /etc/default/cpufrequtils ]; then
  . /etc/default/cpufrequtils
fi

start() {
    /usr/sbin/cpufreq-init.sh ${START_OPTS}
    exit $?
}

stop() {
    /usr/sbin/cpufreq-init.sh "${STOP_OPTS}"
    exit $?
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  status)
    /usr/bin/cpufreq-info
  ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|status}" >&2
    exit 1
  ;;
esac

exit 0

