## extra console apps for new image recipe structure

IMAGE_INSTALL += " \
    zip \
    ntp \
    ntpdate \
    ntp-utils \
    perl-module-socket \
    perl-module-getopt-std \
    usbutils \
    dbus-daemon-proxy \
    nfs-utils-client \
    cifs-utils \
    strace \
    ltrace \
    lsof \
    git \
    htop \
    iptables \
    mbuffer \
    mtd-utils \
    nmon \
    powertop \
    socat \
    sysstat \
    procps \
    serial-forward \
    bluez-hcidump \
    bluez4-agent \
    wpa-supplicant \
    links \
    irssi \
    jack-server \
    jack-utils \
    fluidsynth \
    sox \
    gnuplot \
"
