#!/bin/sh
### BEGIN INIT INFO
# Provides:          consolekit
# Required-Start:    $remote_fs dbus
# Required-Stop:     $remote_fs dbus
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: ConsoleKit daemon for session support
### END INIT INFO

# Copyright 2014 Stephen L Arnold <stephen.arnold42 _at_ gmail.com>
# Distributed under the terms of the GNU General Public License, v2 or later

DAEMON=/usr/sbin/console-kit-daemon
PID=/run/ConsoleKit.pid
DESC="ConsoleKit daemon"

set -e

do_start() {
	start-stop-daemon --start -q --pidfile $PID --exec $DAEMON --
}

do_stop() {
	start-stop-daemon --stop -q --pidfile $PID
}

case "$1" in
  start)
	echo "Starting $DESC"
	do_start
	;;
  stop)
	echo "Stopping $DESC"
	do_stop
	;;
  restart|force-reload)
	echo "Restarting $DESC"
	do_stop
	sleep 1
	do_start
	;;
  *)
	echo "Usage: $0 {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
