#!/bin/bash
### BEGIN INIT INFO
# Provides:          lxdm
# Required-Start:    $remote_fs consolekit
# Required-Stop:     $remote_fs consolekit
# Default-Start:     4 5
# Default-Stop:      0 1 2 3 6
# Short-Description: simple init script for lxdm (runs on VT 7)
### END INIT INFO

# Copyright 2014 Stephen L Arnold <stephen.arnold42 _at_ gmail.com>
# Distributed under the terms of the GNU General Public License, v2 or later

. /etc/init.d/functions

## LANG=C do we need to set this?
PATH=/sbin:/bin:/usr/sbin:/usr/bin

for x in $(cat /proc/cmdline); do
        case $x in
        x11=false)
		echo "X Server disabled" 
		exit 0;
                ;;
        esac
done

NAME=lxdm-binary
EXE=/usr/sbin/lxdm-binary
PIDFILE=/var/run/lxdm.pid
START_STOP_ARGS="--background"

export GDK_USE_XFT=1

case "$1" in
    start)
        # We don't want this script to block the rest of the boot process
        if [ "$2" != "background" ]; then
            $0 $1 background &
        else
            echo "Starting Xserver"
            start-stop-daemon --start --exec ${EXE} --name ${NAME} --pidfile ${PIDFILE} \
                -- ${START_STOP_ARGS}
        fi 
    ;;

    stop)
        echo "Stopping XServer"
        start-stop-daemon --stop --exec ${EXE} --name ${NAME} --pidfile ${PIDFILE}
    ;;

  restart)
	$0 stop
        sleep 1
        $0 start
  ;;

  *)
        echo "usage: $0 { start | stop | restart }"
  ;;
esac

exit 0
